name: Read and format file

on:
  push:
    branches:
      - main

jobs:
  format-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read and format data
      id: format-data
      run: |
        formatted=$(awk '{printf "%-6s %-15s %s-%s %s\n", $1, $2, $4, $3, $5}' data.txt)
        echo "formatted-data=formatted" >> $GITHUB_OUTPUT
        
    - name: Print formatted data
      run: echo "${{ steps.format-data.outputs.formatted-data }}"
