name: Read and format file

on:
  push:
    branches:
      - main

jobs:
  format-data:
    runs-on: ubuntu-latest
    outputs:
      formatted-data: ${{ steps.format-data.outputs.formatted-data }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read and format data
      id: format-data
      run: |
        formatted=$(awk '{printf "%-6s %-15s %s-%s %s\n", $1, $2, $3, $4, $5}' data.txt)
        formatted="${formatted//$'\n'/'%0A'}"
        echo "formatted-data=$formatted" >> $GITHUB_OUTPUT
        
  print-data:
    runs-on: ubuntu-latest
    needs: [format-data]
    steps:
    - name: Print formatted data
      run: echo ${{ steps.format-data.outputs.formatted-data }}
